### ISSUE TITLE
Error when creating a new category

### ISSUE THREAD

**Issue by uskudarli** [gr3ysky/cooperate#7]
![taneryigit_yenikategorihata](https://cloud.githubusercontent.com/assets/1347035/15634169/379c8dde-25c6-11e6-8c60-a65a8988db9a.png)

Hata!
Aradığınız sayfa bulunamadı!
Copyright© Yiyecek Kooperatifi 2016

**Comment by gr3ysky** [comment]
There is a broken link on the form that is posted. 
It is now fixed and working properly.
